language: cpp
env:
  matrix:
    -LUA_VERSION=5.2
before_install:
- sudo apt-get install lua$LUA_VERSION
- sudo pip install docutils
script:
- python travis/pr-check-base.py
- python travis/lint.py
- python travis/luac.py
- ./fixTexts.sh --force
notifications:
    email: false
